git:
  commitMessage: "Release %s"
  tagName: "v${version}"
  requireCleanWorkingDir: false
  requireUpstream: false
npm:
  publish: false
github:
  release: true
  releaseName: "${version}"
  draft: true
  assets:
    - build/*.AppImage
    - build/*.deb
    - build/*.rpm
    - build/*.exe
    - build/*.dmg
