language: node_js
node_js:
  - '10'
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
#    - os: osx
#    - os: windows
cache:
  npm: true
notifications:
  email: false
script:
  - npm run electron:build
