language: node_js
node_js:
  - '10'
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
#    - os: osx
#    - os: windows
cache:
  npm: true
notifications:
  email: false
script:
  - npm run electron:build
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - "build/name-it*.AppImage"
    - "build/name-it*.deb"
  skip_cleanup: true
  on:
    tags: true
